### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by malayakvl** [MultiSafepay/multisafepay-node-wrapper#24]
# Bug report

## Describe the bug
Use MSPClient in my node application. Add lib via import:
import MSPClient from '@multisafepay/api-wrapper';

Error on create client

## To Reproduce
const multiSafePayClient = new MSPClient('apiKey', { environment: 'test' });

## Expected behavior

When try to create client receive error

TypeError: MSPClient is not a constructor

## Screenshots

 - OS: MacOS
 - Node Version: v17.3.0
 - NPM Version: 8.3.0

**Comment by robindelaater** [comment]
Hi @malayakvl,

If you use it like this it should work:
`const multiSafePayClient = new MSPClient('apikey', { environment: 'test' });`

Let me know if it helps.
